---
title: "0_L1"
output: html_notebook
---

```{r}
library(tidyverse)
library(tidyboot)
library(ggthemes)
library(ggpirate)
theme_set(theme_few())
```

```{r}
d.l1 <- read.csv("../data/0_L1/0_L1-trials.csv") %>%
  mutate(sentence_type = factor(sentence_type,
                                levels = c("antonym",
                                           "neg_positive",
                                           "neither_pos_nor_ant",
                                           "neg_antonym",
                                           "positive"),
                                labels = c("Antonym",
                                           "Negated Positive",
                                           "Neither ... nor ...",
                                           "Negated Antonym",
                                           "Positive")))
  
d.l1.time <- read.csv("../data/0_L1/0_L1-time.csv")


d.l1.censored <- left_join(d.l1,
  d.l1.time) %>%
  filter(time > 2)
  
d.l1.comments <- read.csv("../data/0_L1/0_L1-subject_information.csv")
```

```{r}
d.l1 %>%
  filter(sentence_type != "Neither ... nor ...") %>%
ggplot(., aes( x = response,
                       fill = sentence_type))+
  geom_histogram(position = position_dodge())+
  #geom_density(alpha = 0.3)+
  facet_wrap(~sentence_type, nrow = 1)+
  scale_fill_solarized()+
  ylab("counts")+
  xlab("degree ratings")+
  scale_x_continuous(limits = c(-0.01, 1.01), breaks = c(0, 1))+
  guides(fill = F)

ggsave("~/Documents/research/talks/vagueness/negAnt_histograms.pdf", 
       width = 6, height = 3)
```



```{r}
d.l1.boot <- d.l1 %>%
  group_by(sentence_type) %>%
  multi_boot_standard(col = "response")
```

```{r}
d.l1.boot %>%
ggplot(., aes(x = sentence_type,
                      y = mean,
                       ymin = ci_lower, ymax = ci_upper,
                       fill = sentence_type,
              group = sentence_type))+
  geom_hline(yintercept = 0.5, lty = 3)+
  geom_col(position = position_dodge(0.5), width = 0.8, color = 'black')+
  geom_errorbar(position = position_dodge(0.5), color = 'black',
                width = 0.3)+
  scale_fill_solarized()+
  #coord_flip()+
  #guides(fill = F)+
  xlab("")+
  ylab("interpreted degree")+
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.5,1))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))+
  guides(fill = F)

ggsave("~/Documents/research/talks/vagueness/cusp-2017/not-unhappy_bootstrapped.pdf", width = , height = 3.5)
```

```{r}
d.l1.boot %>%
  mutate(x = 1) %>%
ggplot(., aes(x = x,
                      y = mean,
                       ymin = ci_lower, ymax = ci_upper,
                       fill = sentence_type,
              group = sentence_type))+
  geom_hline(yintercept = 0.5, lty = 3)+
  geom_col(position = position_fill())+
  #geom_errorbar(position = position_dodge(0.8), color = 'black',
                #width = 0.3)+
  scale_fill_solarized()+
  #coord_flip()+
  #guides(fill = F)+
  xlab("")+
  ylab("interpreted degree")+
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.5,1))
```


```{r}

d.l1.boot.adj <- d.l1 %>%
  group_by(positive, sentence_type)  %>%
  multi_boot_standard(col = "response")

d.l1.boot.adj %>%
ggplot(., aes(x = positive,
                      y = mean,
                       ymin = ci_lower, ymax = ci_upper,
                       fill = sentence_type,
              group = sentence_type))+
  geom_hline(yintercept = 0.5, lty = 3)+
  geom_col(position = position_dodge(0.8), width = 0.8, color = 'black')+
  geom_errorbar(position = position_dodge(0.8), color = 'black',
                width = 0.3)+
  scale_fill_solarized()+
  #coord_flip()+
  #guides(fill = F)+
  xlab("")+
  ylab("interpreted degree")+
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.5,1))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

```


```{r}
d.l1.boot.adj %>%
  filter(sentence_type %in% 
           c("Negated Positive", "Antonym"),
         positive %in% c("attractive", "happy",
                         "interesting", "polite")) %>%
ggplot(., aes(x = positive,
                      y = mean,
                       ymin = ci_lower, ymax = ci_upper,
                       fill = sentence_type,
              group = sentence_type))+
  geom_hline(yintercept = 0.5, lty = 3)+
  geom_col(position = position_dodge(0.8), width = 0.8, color = 'black')+
  geom_errorbar(position = position_dodge(0.8), color = 'black',
                width = 0.3)+
  scale_fill_solarized()+
  #coord_flip()+
  #guides(fill = F)+
  xlab("")+
  ylab("interpreted degree")+
  scale_y_continuous(limits = c(0,0.5), breaks = c(0, 0.5))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

ggsave("~/Documents/research/talks/vagueness/cusp-2017/explore-items.pdf", width = 5, height = 3.5)

```

