---
title: "2_L1"
output: github_document
---

```{r}
library(tidyverse)
library(tidyboot)
library(ggthemes)
library(ggpirate)
library(langcog)
library(knitr)
theme_set(theme_few())
```

```{r}
d.l1 <- read.csv("../data/2_L1_oneslider/2_L1_oneslider-trials.csv") %>%
  mutate(sentence_type = factor(sentence_type,
                                levels = c("antonym",
                                           "neg_positive",
                                           "neither_pos_nor_ant",
                                           "neg_antonym",
                                           "positive"),
                                labels = c("Antonym",
                                           "Negated Positive",
                                           "Neither ... nor ...",
                                           "Negated Antonym",
                                           "Positive")))
  
d.l1.time <- read.csv("../data/2_L1_oneslider/2_L1_oneslider-time.csv")

summary(d.l1)
```



Time to complete task

```{r}
ggplot(d.l1.time, aes(x = time)) +
  geom_histogram()+
  xlab("time in minutes")
```


```{r}
d.l1.censored <- left_join(d.l1,
  d.l1.time) %>%
  filter(time > 2)
  
d.l1.comments <- read.csv("../data/2_L1_oneslider/2_L1_oneslider-subject_information.csv")

d.l1.comments %>% select(comments) %>% filter(comments != "") %>% kable()
```


```{r}
d.l1 %>%
  filter(sentence_type != "Neither ... nor ...") %>%
ggplot(., aes( x = response,
                       fill = sentence_type))+
  geom_histogram(position = position_dodge(), bins = 20)+
  #geom_density(alpha = 0.3)+
  facet_wrap(~sentence_type, nrow = 1)+
  scale_fill_solarized()+
  ylab("counts")+
  xlab("degree ratings")+
  scale_x_continuous(limits = c(-0.01, 1.01), breaks = c(0, 1))+
  guides(fill = F)

ggsave("~/Documents/research/talks/vagueness/frisem-2018-01/img/negAnt_morpho2_histograms.pdf",
       width = 7, height = 3)
```


```{r}
lm.2 <- lmer(response ~ sentence_type * positive + 
               (1 | workerid), 
     data = d.l1)
summary(lm.2)
```

```{r}
d.l1.boot <- d.l1 %>%
  group_by(sentence_type) %>%
  multi_boot_standard(col = "response")
```

```{r}
d.l1.boot %>%
    filter(sentence_type != "Neither ... nor ...") %>%
  ggplot(., aes(x = sentence_type,
                      y = mean,
                       ymin = ci_lower, ymax = ci_upper,
                       fill = sentence_type,
              group = sentence_type))+
  geom_hline(yintercept = 0.5, lty = 3)+
  geom_col(position = position_dodge(0.5), width = 0.8, color = 'black')+
  geom_errorbar(position = position_dodge(0.5), color = 'black',
                width = 0.3)+
  scale_fill_solarized()+
  #coord_flip()+
  #guides(fill = F)+
  xlab("")+
  ylab("interpreted degree")+
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.5,1))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))+
  guides(fill = F)

ggsave("~/Documents/research/talks/vagueness/frisem-2018-01/img/negant_morpho2_bootstrapped.pdf", width = 4, height = 3.5)
```

```{r echo = F, eval = F}
d.l1.boot %>%
  mutate(x = 1) %>%
  ggplot(., aes(x = x,
                      y = mean,
                       ymin = ci_lower, ymax = ci_upper,
                       fill = sentence_type,
              group = sentence_type))+
  geom_hline(yintercept = 0.5, lty = 3)+
  geom_col(position = position_fill())+
  #geom_errorbar(position = position_dodge(0.8), color = 'black',
                #width = 0.3)+
  scale_fill_solarized()+
  #coord_flip()+
  #guides(fill = F)+
  xlab("")+
  ylab("interpreted degree")+
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.5,1))
```


```{r}

d.l1.boot.adj <- d.l1 %>%
  group_by(positive, sentence_type)  %>%
  multi_boot_standard(col = "response")

d.l1.boot.adj %>%
      filter(sentence_type != "Neither ... nor ...") %>%
ggplot(., aes(x = positive,
                      y = mean,
                       ymin = ci_lower, ymax = ci_upper,
                       fill = sentence_type,
              group = sentence_type))+
  geom_hline(yintercept = 0.5, lty = 3)+
  geom_col(position = position_dodge(0.8), width = 0.8, color = 'black')+
  geom_errorbar(position = position_dodge(0.8), color = 'black',
                width = 0.3)+
  scale_fill_solarized()+
  #coord_flip()+
  #guides(fill = F)+
  xlab("")+
  ylab("interpreted degree")+
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.5,1))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

ggsave("~/Documents/research/talks/vagueness/frisem-2018-01/img/negant_morpho2_bootstrapped_item.pdf", width = 8, height = 3.5)
```


```{r}
d.l1.boot.adj %>%
  filter(sentence_type %in% 
           c("Negated Positive", "Antonym"),
         positive %in% c("attractive", "happy",
                         "interesting", "polite")) %>%
ggplot(., aes(x = positive,
                      y = mean,
                       ymin = ci_lower, ymax = ci_upper,
                       fill = sentence_type,
              group = sentence_type))+
  geom_hline(yintercept = 0.5, lty = 3)+
  geom_col(position = position_dodge(0.8), width = 0.8, color = 'black')+
  geom_errorbar(position = position_dodge(0.8), color = 'black',
                width = 0.3)+
  scale_fill_solarized()+
  #coord_flip()+
  #guides(fill = F)+
  xlab("")+
  ylab("interpreted degree")+
  scale_y_continuous(limits = c(0,0.5), breaks = c(0, 0.5))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

#ggsave("~/Documents/research/talks/vagueness/cusp-2017/explore-items.pdf", width = 5, height = 3.5)

```


First half vs. second half split

```{r}
d.l1.splithalf <- d.l1 %>%
  mutate(splitHalf = ifelse(trial_num <= 15, "first", "second")) %>%
  #filter(negation == "morphological") %>%
  group_by(workerid, sentence_type) %>%
  group_by(sentence_type, splitHalf) %>%
  multi_boot_standard(col = 'response')


ggplot(d.l1.splithalf, aes(x = splitHalf, fill = sentence_type,
                                  y = mean, ymin = ci_lower,
                                  ymax = ci_upper))+
  geom_col(position = position_dodge(), color = 'black')+
  geom_errorbar(position = position_dodge())

ggsave("~/Documents/research/negant/analysis/figs/split_half-2_L1.pdf", width =6 , height = 4)
```


