---
title: "5_L1"
output: github_document
---


```{r}
library(tidyverse)
library(tidyboot)
library(ggthemes)
library(ggpirate)
library(langcog)
library(knitr)
library(lme4)
library(lmerTest)
theme_set(theme_few())

project.prefix <- "5_L1_4sliders"
```

```{r}
d.l1.5 <- read.csv(paste("../data/",project.prefix,"/",project.prefix,"-trials.csv", sep = "")) %>%
  mutate(sentence_type = factor(sentence_type,
                                levels = c("antonym",
                                           "neg_positive",
                                           "neg_antonym",
                                           "positive"),
                                labels = c("Antonym",
                                           "Negated Positive",
                                           "Negated Antonym",
                                           "Positive")))
  
d.l1.5.time <- read.csv(paste("../data/",project.prefix,"/",project.prefix,"-time.csv", sep = ""))

```



Time to complete task

```{r}
ggplot(d.l1.5.time, aes(x = time)) +
  geom_histogram()+
  xlab("time in minutes")
```


```{r}
d.l1.5.comments <- read.csv(paste("../data/",project.prefix,"/",project.prefix,"-subject_information.csv", sep =""))

d.l1.5.comments %>% select(comments) %>% filter(comments != "") %>% kable()
```

```{r}
d.l1.5 %>%
  ggplot(., aes( x = response,
                       fill = sentence_type))+
  geom_histogram(position = position_dodge(), bins = 20)+
  #geom_density(alpha = 0.3)+
  facet_grid(negation~sentence_type)+
  scale_fill_solarized()+
  ylab("counts")+
  xlab("slider ratings")+
  scale_x_continuous(limits = c(-0.01, 1.01), breaks = c(0, 1))+
  guides(fill = F)

# ggsave(paste(
#   "~/Documents/research/talks/vagueness/frisem-2018-01/img/", project.prefix, "_histograms.pdf", sep = ""),
#        width = 7, height = 3)
```

## Bootstrapped CIs


```{r}
d.l1.5.boot <- d.l1.5 %>%
  group_by(negation, sentence_type) %>%
  multi_boot_standard(col = "response")
```

```{r}
d.l1.5.boot %>%
ggplot(., aes(x = negation,
                      y = mean,
                       ymin = ci_lower, ymax = ci_upper,
                       fill = sentence_type,
              group = sentence_type
              ))+
  geom_hline(yintercept = 0.5, lty = 3)+
  geom_col(position = position_dodge(0.5), width = 0.5, color = 'black')+
  geom_errorbar(position = position_dodge(0.5), color = 'black',
                width = 0.3)+
  scale_fill_solarized()+
  #coord_flip()+
  #facet_wrap(~negation)+
  guides(fill = F)+
  xlab("")+
  ylab("interpreted degree")+
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.5,1))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

# ggsave(paste(
#   "~/Documents/research/talks/vagueness/frisem-2018-01/img/", project.prefix, "_bootstrapped.pdf", sep = ""),
#        width = 7, height = 3)
```

## By item

```{r fig.width = 7, fig.height = 3}

d.l1.5.boot.adj <- d.l1.5 %>%
  group_by(negation, positive, sentence_type)  %>%
  multi_boot_standard(col = "response")

d.l1.5.boot.adj %>%
  ggplot(., aes(x = positive,
                      y = mean,
                       ymin = ci_lower, ymax = ci_upper,
                       fill = sentence_type,
              group = sentence_type))+
  geom_hline(yintercept = 0.5, lty = 3)+
  geom_col(position = position_dodge(0.8), width = 0.8, color = 'black')+
  geom_errorbar(position = position_dodge(0.8), color = 'black',
                width = 0.3)+
  scale_fill_solarized()+
  facet_wrap(~negation, scales = 'free') + 
  #coord_flip()+
  #guides(fill = F)+
  xlab("")+
  ylab("interpreted degree")+
  scale_y_continuous(limits = c(0,1), breaks = c(0, 0.5,1))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

#ggsave("~/Documents/research/talks/vagueness/frisem-2018-01/img/negant_lexical_bootstrapped_item.pdf", width = 8, height = 3.5)
```

# Regression models

```{r}

d.l1.5 <- within(d.l1.5, {
  st <- C(sentence_type, helmert, 3)
  print(attributes(st))
})

d.l1.5 <- d.l1.5 %>% 
  mutate(negation = factor(negation, 
                           levels = c("morphological", "lexical")))

# rs.5.helmert.0 <- lmer(response ~ negation * st + 
#                        (1 | workerid) + 
#                        (1 | positive),
#                      data = d.l1.5)
# 
# rs.5.helmert.1 <- lmer(response ~ negation * st + 
#                        (1 | workerid) + 
#                        (1 + st | positive),
#                      data = d.l1.5)
# 
# anova(rs.5.helmert.0, rs.5.helmert.1)
# 
# rs.4.helmert.2 <- lmer(response ~ negation * st + 
#                        (1 + st | workerid) + 
#                        (1 | positive),
#                      data = d.l1.4)
# anova(rs.4.helmert.0, rs.4.helmert.2)


rs.5.helmert.3 <- lmer(response ~ negation * st + 
                       (1 + st | workerid) + 
                       (1 + st | positive),
                     data = d.l1.5)

# anova(rs.4.helmert.2, rs.4.helmert.3)
# anova(rs.4.helmert.1, rs.4.helmert.3)

summary(rs.5.helmert.3)
```

```{r}

rs.5.helmert.0.simple <- lmer(response ~ st + 
                       (1 + st | workerid) + 
                       (1 + st | positive),
                     data = d.l1.5 %>% 
                       filter(negation == "morphological")
                     )

summary(rs.5.helmert.0.simple)
```

```{r reg.simple.lex}

rs.5.helmert.0.simple.lex <- lmer(response ~ st + 
                       (1 + st | workerid) + 
                       (1 + st | positive),
                     data = d.l1.5 %>% 
                       filter(negation == "lexical")
                     )

summary(rs.4.helmert.0.simple.lex)
```


## 3-way interaction with task type?

```{r}
d.l1.4.5 <- bind_rows(
  d.l1.5 %>% 
    mutate(src= '4slider'),
  d.l1.4 %>%
    mutate(src = '1slider')
) %>% mutate(src = factor(src, levels = c("1slider", "4slider")))


d.l1.4.5 <- within(d.l1.4.5, {
  st <- C(sentence_type, helmert, 3)
  print(attributes(st))
})

rs.4.5.helmert.0 <- lmer(response ~ negation * st * src + 
                       (1 + st | workerid) + 
                       (1 + st | positive),
                     data = d.l1.4.5)

summary(rs.4.5.helmert.0)
```



## Exploratory stuff

### Spilt half

```{r}
d.l1.4.splithalf <- d.l1.4 %>%
  mutate(splitHalf = ifelse(trial_num <= 8, "first", "second")) %>%
  group_by(negation, sentence_type, splitHalf) %>%
  multi_boot_standard(col = 'response')

ggplot(d.l1.4.splithalf,
       aes(x = splitHalf, fill = sentence_type,
                                  y = mean, ymin = ci_lower,
                                  ymax = ci_upper))+
  geom_col(position = position_dodge(), color = 'black')+
  scale_fill_solarized()+
  geom_errorbar(position = position_dodge())+
  facet_wrap(~negation)
```

### First vs. last rating

```{r}

d.l1.4.first.last <- bind_rows(
  d.l1.4 %>%
    group_by(workerid, negation, sentence_type) %>%
    top_n(1, -trial_num) %>%
    mutate(presentation = 'first'),
  d.l1.4 %>%
    group_by(workerid, negation, sentence_type) %>%
    top_n(1, trial_num) %>%
    mutate(presentation = 'last')
)
  

d.l1.4.first.last.summary <- d.l1.4.first.last %>%
  group_by(negation, sentence_type, presentation) %>%
  multi_boot_standard(col = 'response')

ggplot(d.l1.4.first.last.summary, aes(x = presentation, fill = sentence_type,
                                  y = mean, ymin = ci_lower,
                                  ymax = ci_upper))+
  geom_col(position = position_dodge(), color = 'black')+
  geom_errorbar(position = position_dodge())+
  facet_wrap(~negation)

#ggsave("~/Documents/research/negant/analysis/figs/split_half-3_L1.pdf", width =6 , height = 4)
```