---
title: "Understanding the model"
output: html_notebook
---


```{r}
library(rwebppl)
library(jsonlite)
library(ggthemes)
library(tidyverse)
theme_set(theme_few())
```

```{r utils}
utils <- '
var round = function(x){
  return Math.round(x*100)/100
}

var isNegation = function(utt){
  return (utt.split("_")[0] == "not")
};

var avoidEnds = function(x){
  return x >= 1 ? 0.99 : x == 0 ? 0.01 : x
}

var lb = 0, ub = 1, diff = 0.05;
var bins = _.range(lb, ub + diff, diff)

var DiscreteGaussian = function(mu, sigma){
  Infer({model: function(){
    categorical({
      vs:bins,
      ps:map(function(x){Math.exp(Gaussian({mu, sigma}).score(x))}, bins)
    })
  }})
}

var DiscreteBeta = function(a, b){
  Infer({model: function(){
    categorical({
      vs:bins,
      ps:map(function(x){
        Math.exp(Beta({a, b}).score(avoidEnds(x)))
      }, bins)
    })
  }})
}

'
```


```{r language}
language <- '
var utterances = [
  "happy",
  "not_unhappy",
  "not_happy",
  "unhappy",
  // "neither_nor"
];

var cost_yes = 0;
var cost_neg = 1;

var uttCosts = map(function(u) {
  return isNegation(u) ? Math.exp(-cost_neg) : Math.exp(-cost_yes)
}, utterances)

var utterancePrior = Infer({model: function(){
  return utterances[discrete(uttCosts)]
}});


var meaning = function(words, state, thresholds){
  return words == "happy" ? state > thresholds.happy :
  words == "not_happy" ? !(state > thresholds.happy) :
  words == "unhappy" ? state < thresholds.unhappy :
  words == "not_unhappy" ? !(state < thresholds.unhappy) :
  words == "neither_nor" ? (
    !(state > thresholds.happy) &&
    !(state < thresholds.unhappy)
  ) :
  true
};
'
```



```{r}
rsa <- '
var speakerOptimality = 1;
var speakerOptimality2 = 1;

var listener0 = cache(function(utterance, thresholds) {
  Infer({model: function(){
    var state = sample(DiscreteBeta(1, 1));
    // var state = sample(DiscreteGaussian(0, 0.5));
    var m = meaning(utterance, state, thresholds);
    condition(m);
    return state;
  }})
}, 10000);

var speaker1 = cache(function(state, thresholds) {
  Infer({model: function(){
    var utterance = sample(utterancePrior);
    var L0 = listener0(utterance, thresholds);
    factor(speakerOptimality*L0.score(state));
    return utterance;
  }})
}, 10000);

var greaterThanThresholdBins = _.range(lb, ub, diff)
var lessThanThresholdBins = _.range(lb+diff, ub+diff, diff)

var listener1 = cache(function(utterance) {
  Infer({model: function(){
    var thresholds = {
      happy: uniformDraw(greaterThanThresholdBins),
      unhappy: uniformDraw(lessThanThresholdBins)
    }

    var state = sample(DiscreteBeta(1, 1));
    // var state = sample(DiscreteGaussian(0, 0.5));

    var S1 = speaker1(state, thresholds)
    observe(S1, utterance)
    return state
  }})
}, 10000);
'

listenerCall <- '
_.fromPairs(map(function(u){
  var post = listener1(u)
  return [u, post]
}, utterances))
'

speakerCall <- '
_.flatten(_.flatten(
map(function(tH){
  map(function(tU){
    map(function(s){
      var speakProbs = speaker1(s, {happy: tH, unhappy: tU})
       return {  
          state: s,
          happy_theta:tH, 
          unhappy_theta:tU, 
          "happy": Math.exp(speakProbs.score("happy")),
          "unhappy": Math.exp(speakProbs.score("unhappy")),
          "not_unhappy": Math.exp(speakProbs.score("not_unhappy")),
          "not_happy": Math.exp(speakProbs.score("not_happy"))
        }
    }, bins)
  }, lessThanThresholdBins)
}, greaterThanThresholdBins)
))
'
```

```{r}
rs.wp <- webppl(paste(utils, language, rsa, speakerCall,  sep = '\n'))

rs.tidy <- data.frame(rs.wp) %>%
  gather(utt, prob, -state, -happy_theta, -unhappy_theta)
```


Faceting by thresholds
```{r fig.width = 16, fig.height = 3.5}
ggplot(rs.tidy, aes( x = state, y = prob, color = utt))+
  geom_line()+
  scale_color_solarized()+
  facet_grid(unhappy_theta~happy_theta)+
  scale_x_continuous(breaks = c(0, 0.5, 1))+
  scale_y_continuous(breaks = c(0, 0.5, 1))

#ggsave("figs/S1_uttXstateXthetas_wCost.pdf", width = 20, height = 14)
```


Marginalizing out thresholds

```{r}
rs.marginal <- rs.tidy %>%
  group_by(state, utt) %>%
  summarize(marginalProb = mean(prob))


ggplot(rs.marginal, aes( x = state, y = marginalProb, color = utt))+
  geom_line(size = 1.2)+
  scale_color_solarized()+
  xlab("Degree of happiness")+
  ylab("Speaker utterance production probability")+
  scale_x_continuous(breaks =c(0, 1))+
  scale_y_continuous(breaks = c(0, 0.5))

#ggsave("figs/S1_uttMarginals_wCost.png", width = 6, height = 3.7)
```

"Not Unhappy" is semantically equivalent to "happy". The higher the state, the more likely "happy" (and "not unhappy") is to be produced by a speaker (because it's more likely to be true, given the uniform priors on thresholdse). 

In the midpoint, "happy" / "not unhappy" is less true, and "unhappy"/ "not happy" is more true. 

```{r}
rs.listener.wp <- webppl(paste(utils, language, rsa, listenerCall,  sep = '\n'))

rs.listener.wp.tidy <- bind_rows(
  data.frame(rs.listener.wp$happy) %>% 
    mutate(utterance = "happy"),
  data.frame(rs.listener.wp$unhappy) %>% 
    mutate(utterance = "unhappy"),
  data.frame(rs.listener.wp$not_unhappy) %>% 
    mutate(utterance = "not_unhappy"),
  data.frame(rs.listener.wp$not_happy) %>% 
    mutate(utterance = "not_happy")
)


rs.listener.wp.tidy.samples <- get_samples(
  rs.listener.wp.tidy %>% rename(prob = probs), 10000)

ggplot(rs.listener.wp.tidy.samples, 
       aes( x = support,fill = utterance, color = utterance))+
  geom_density(alpha = 0.4, size = 1.3)+
  scale_fill_solarized()+
  scale_color_solarized()+
  xlab("Degree of happiness")+
  ylab("Posterior probability density")+
  scale_x_continuous(breaks =c(0, 1))+
  scale_y_continuous(breaks = c(0, 2))

#ggsave("figs/L1_posteriors_wCost.png", width = 6, height = 4)
```

